language: ruby
sudo: false

rvm:
  - 2.3.6
  - 2.4.4
  - 2.5.1

jobs:
  include:
    - stage: redeploy-app
      script: skip
      deploy: &heroku
        provider: heroku
        app: gem-rails-ohmy
        api_key: $HEROKU_AUTH_TOKEN
        strategy: api

before_deploy:
  - mkdir build
  - cd build
  - git clone https://github.com/travis-ci/rails-demo
  - cd ./rails-demo

before_install:
  - gem update --system
  - gem install bundler

install: bundle install --retry=3


