language: ruby
sudo: false

rvm:
  - 2.3.6
  - 2.4.4
  - 2.5.1

jobs:
  include:
    - stage: redeploy-app
      script: skip
      deploy:
        provider: script
        script: bash deploy.sh
        on: 
          branch: master

before_install:
  - gem update --system
  - gem install bundler

install: bundle install --retry=3


